### ISSUE TITLE
exiftool_arg.txt error

### ISSUE THREAD

**Issue by cooperd1958** [Nordlien/PhotoTags-Synchronizer#6]
**Describe the bug**
I get the error below when I save changes.

Error Message: Error opening arg file C:\Users\coope\AppData\Local\PhotoTagsSynchronizer\exiftool_arg.txt

Actual location for arg file is:
C:\Users\user\AppData\Local\Packages\36037Nordlien.PhotoTags-Synchronizer_1xds7jjrydn34\LocalCache\Local\PhotoTagsSynchronizer\exiftool_arg.txt

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I installed application from Windows Store ~2 weeks ago.

**Comment by Nordlien** [comment]
Thanks for letting me know. Sorry for this has happen, I have only one computer to test on, so world wide user a "my testers" also.
I will look into it and check why and then I will try to fix it.

**Comment by cooperd1958** [comment]
Thanks.  Let me know if you need additional information or I can help.

What is the best way to let you know about other issues?
________________________________

**Comment by Nordlien** [comment]
I'm trying to find the issue, but it works fine for others and on my
computer. Need to try figure out what's different on your computer.

Does it happen all the time?
Can you send the logs.
Are there any special settings in windows you using?

Best regards Nordlien

man. 20. feb. 2023, 17:04 skrev cooperd1958 ***@***.***>:

**Comment by cooperd1958** [comment]
After doing the following, I get the same error:

  *   Uninstall PhotoTags
  *   Updated all drivers
  *   Cleared all temporary files
  *   Repaired registry
  *   Reset Microsoft Store App
  *   Installed PhotoTags

I also installed a few other apps from Micosoft Store, one to change date on image files.  I was able to change the date on the file in the error message below.



Issue: EXIFTOOL.EXE failed write to file.
File Name:  C:\C_Temp_XPS\LightroomExports\20221116_0829\20221113_094311.jpg
File Status:
File Attributes: Archive
Creation Time: 11/16/2022 8:29:55 AM
Last Write Time: 11/16/2022 8:29:55 AM
Error Message: Error opening arg file C:\Users\coope\AppData\Local\PhotoTagsSynchronizer\exiftool_arg.txt


exiftool_arg.txt is located here:

C:\Users\coope\AppData\Local\Packages\36037Nordlien.PhotoTags-Synchronizer_1xds7jjrydn34\LocalCache\Local\PhotoTagsSynchronizer\exiftool_arg.txt

PhotoTags log and Microsoft Store event viewer (cleared before PhotoTags install) are attached.
________________________________

**Comment by Nordlien** [comment]
Hi again,
Thanks for helping out improve the product and for helping you get a "working" product.

One way to find the issue is to create a Zoom or Goole Meet where we can work together to find why this is happening.
I'm living in CET time zone. Let me know if that will be ok.

Or we can try by doing this:

Will you be able to turn on higher level of logging.

## Logging
1. Turn on Trace level of logging, and delete old files if too long, 
2. Click save (Restart the application, just incase)
![image](https://user-images.githubusercontent.com/72686779/220288833-41acc59e-94ed-48a8-a3c6-d4dfe7ec4389.png)

Updated the file with Metadata on your picture, then logging will contain more info about this process.

3. Select all the text logged and Copy the text and send to me
![image](https://user-images.githubusercontent.com/72686779/220286522-8c759c15-686b-4d29-95e8-5261dc996dc0.png)

**Question 1:** 
Will you be able to send the log text to me?

## Files

After trying to write to this file:  C:\C_Temp_XPS\LightroomExports\20221116_0829\20221113_094311.jpg

**Question 2:** 
What files do you have in this folder(s): 
- C:\Users\coope\AppData\Local\PhotoTagsSynchronizer
- C:\Users\coope\AppData\Local\Packages\36037Nordlien.PhotoTags-Synchronizer_1xds7jjrydn34\LocalCache\Local\PhotoTagsSynchronizer\

**Question 3:** 
Info about this file exiftool_arg.txt: 
- C:\Users\coope\AppData\Local\PhotoTagsSynchronizer\exiftool_arg.txt
- C:\Users\coope\AppData\Local\Packages\36037Nordlien.PhotoTags-Synchronizer_1xds7jjrydn34\LocalCache\Local\PhotoTagsSynchronizer\exiftool_arg.txt
a) Can you open and edit the file with notepad and save it? 
b) What's last written date and time?
c) Is there any restriction on the folder. Any limitation on Read / Write access? 
d) I don't believe it, but maybe a AntiVirus protection software that stop access this folder?

**Question 4:**
If you use another computer can you then update the image metadata?


## Info:
This is correct folder where exiftool_arg.txt should be create and read, also contains the database and more files: 
%AppData%\..\Local\PhotoTagsSynchronizer
![image](https://user-images.githubusercontent.com/72686779/220290761-d67bdd5f-74cc-42cf-87b7-abd811126fca.png)

On my computer I only get one exiftool_arg.txt file.
![image](https://user-images.githubusercontent.com/72686779/220293620-e860047e-d96d-4b76-a35e-4c5eacf753c9.png)

**Comment by cooperd1958** [comment]
Did you receive the email with my answers?
________________________________

**Comment by Nordlien** [comment]
Hi, I didn't get the previous message.
Will 19:00 CET (Central Europe Time), I guess that's 10:00 am in California work for you tomorrow, on Monday?

**Comment by cooperd1958** [comment]
Yes that time works for me.   Send me a link.
________________________________

**Comment by Nordlien** [comment]
Hi,

If you open the communication thread in [github/](https://github.com/Nordlien/PhotoTags-Synchronizer/issues/6)
You should see the link. Inside the mail client you will not see it.

Video call link: [https://meet.google.com/mxk-anwk-zgj](https://meet.google.com/mxk-anwk-zgj)

**Comment by cooperd1958** [comment]
Answers are attached.  
[Answers.pdf](https://github.com/Nordlien/PhotoTags-Synchronizer/files/10841913/Answers.pdf)

**Comment by Nordlien** [comment]
Did we solve this issues for you:
1) Access to folder - so files exiftool temp files was able to created and written to?
2) Solution for showing text inside Grid
